#! /bin/bash

if [ $# -ne 1 ]
then
    echo "Usage - gmit  message"
    exit 1
fi

path=$OCTOPRESS_HOME
cd "$path"
#pwd
git add .
git commit -m "$1"
git push origin source
echo "git commit and push ok"