#! /bin/bash

if [ $# -ne 1 ]
then
    echo "Usage - newpage  pagename"
    exit 1
fi

path=$OCTOPRESS_HOME
cd "$path"
echo "$path"
filepath=`rake new_page["$1"]`
echo "$filepath"
#Creating new page: source/projects/index.markdown
OLD_IFS="$IFS"
IFS=" "
arr=($filepath)
filepath=${arr[3]}
IFS="$OLD_IFS"
postpath="$path/$filepath"
echo "$postpath"
#open Mou with the file
open -a Mou $postpath
